SurveyME/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using SurveyME.ModelViews;

namespace SurveyME.Controllers
{
    public class SectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Sections
        public ActionResult Index(int? page, string surveyform_id)
        {
            int passed_surveyformid = Convert.ToInt32(surveyform_id);
            var filteredsectionslist = db.Sections_Dbset.Where(x => x.SurveyForm_Id.Equals(passed_surveyformid)).ToList().ToPagedList(page ?? 1, 1);
            var filteredbinarylist = db.BinaryChoices_Dbset.Where(x => x.SurveyForm_Id.Equals(passed_surveyformid)).ToList();

            CompleteSectionViewModel groupmodel = new CompleteSectionViewModel();
            groupmodel.sectionslist = filteredsectionslist;
            groupmodel.binarychoicelist = filteredbinarylist;
            return View(groupmodel);
        }

        // GET: Sections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sections sections = await db.Sections_Dbset.FindAsync(id);
            if (sections == null)
            {
                return HttpNotFound();
            }
            return View(sections);
        }

        // GET: Sections/Create
        public ActionResult Create(string surveyform_id)
        {
            TempData["temp_surveyformid"] = surveyform_id;
            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,SurveyForm_Id,UserName,Editor,DateofCreation,DateofModification,IPAddress,SectionTitle,SectionDescription")] Sections sections)
        {
            if (ModelState.IsValid)
            {
                int passed_surveyformid = Convert.ToInt32(TempData["temp_surveyformid"]);

                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                sections.UserName = user.UserName;
                sections.DateofCreation = DateTime.Now.ToUniversalTime();
                sections.IPAddress = Request.UserHostAddress;
                sections.SurveyForm_Id = passed_surveyformid;

                db.Sections_Dbset.Add(sections);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { surveyform_id = passed_surveyformid });
            }

            return View(sections);
        }

        // GET: Sections/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sections sections = await db.Sections_Dbset.FindAsync(id);
            if (sections == null)
            {
                return HttpNotFound();
            }
            return View(sections);
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,SurveyForm_Id,UserName,DateofCreation,IPAddress,SectionTitle,SectionDescription")] Sections sections)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var original_data = db.Sections_Dbset.AsNoTracking().Where(x => x.Id == sections.Id).FirstOrDefault();

                sections.SurveyForm_Id = original_data.SurveyForm_Id;
                sections.UserName = original_data.UserName;
                sections.DateofCreation = original_data.DateofCreation;
                
                sections.Editor = user.UserName;
                sections.DateofModification = DateTime.Now.ToUniversalTime();
                sections.IPAddress = Request.UserHostAddress;

                db.Entry(sections).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sections);
        }

        // GET: Sections/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sections sections = await db.Sections_Dbset.FindAsync(id);
            if (sections == null)
            {
                return HttpNotFound();
            }
            return View(sections);
        }

        // POST: Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Sections sections = await db.Sections_Dbset.FindAsync(id);
            db.Sections_Dbset.Remove(sections);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SurveyME/Controllers/SurveyFormsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using SurveyME.ModelViews;

namespace SurveyME.Controllers
{
    public class SurveyFormsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SurveyForms
        public ActionResult Index(int? page)
        {
            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            return View(db.SurveyForms_Dbset.OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
        }

        public ActionResult MySurveys(int? page)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string currentUserName = User.Identity.GetUserName();
            var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);
            string capturedUserName = user.UserName;

            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            return View(db.SurveyForms_Dbset.Where(s => s.UserName.Equals(capturedUserName)).OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
        }

        public ActionResult MainArea(int? page, string theministry)
        {
            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            if (theministry == null)
            {
                return View(db.SurveyForms_Dbset.OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
            }
            else
            {
                return View(db.SurveyForms_Dbset.Where(s => s.MinistryName.Contains(theministry)).OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
            }
        }

        // GET: SurveyForms/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // GET: SurveyForms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SurveyForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserName,Editor,FirstName,LastName,DateofCreation,DateofModification,IPAddress,ProjectName,MinistryName,SurveyTitle,SurveyDescription,MainResearchArea,ResearchArea,Male_gender,Female_gender,Non_binary_gender,Age_group_A,Age_group_B,Age_group_C,Age_group_D,Age_group_E,Target_PWDs,Status_Single,Status_Married,Academic_Level_Primary,Academic_Level_Secondary,Academic_Level_Diploma,Academic_Level_Degree,Academic_Level_Masters,Academic_Level_PhD")] SurveyForms surveyForms)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var researcharea = surveyForms.ResearchArea;
                var mainresearcharea = db.ResearchArea_Dbset.Where(x => x.Actual_ResearchArea.Equals(researcharea)).SingleOrDefault();

                surveyForms.UserName = user.UserName;
                surveyForms.FirstName = user.FirstName;
                surveyForms.LastName = user.LastName;
                surveyForms.DateofCreation = DateTime.Now.ToUniversalTime();
                surveyForms.IPAddress = Request.UserHostAddress;
                surveyForms.MainResearchArea = mainresearcharea.MainArea;

                db.SurveyForms_Dbset.Add(surveyForms);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(surveyForms);
        }

        // GET: SurveyForms/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // POST: SurveyForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserName,Editor,FirstName,LastName,DateofCreation,DateofModification,IPAddress,ProjectName,MinistryName,SurveyTitle,SurveyDescription,MainResearchArea,ResearchArea,Male_gender,Female_gender,Non_binary_gender,Age_group_A,Age_group_B,Age_group_C,Age_group_D,Age_group_E,Target_PWDs,Status_Single,Status_Married,Academic_Level_Primary,Academic_Level_Secondary,Academic_Level_Diploma,Academic_Level_Degree,Academic_Level_Masters,Academic_Level_PhD")] SurveyForms surveyForms)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var original_data = db.SurveyForms_Dbset.AsNoTracking().Where(x => x.Id == surveyForms.Id).FirstOrDefault();

                var researcharea = surveyForms.ResearchArea;
                var mainresearcharea = db.ResearchArea_Dbset.Where(x => x.Actual_ResearchArea.Equals(researcharea)).SingleOrDefault();

                surveyForms.UserName = original_data.UserName;
                surveyForms.FirstName = original_data.FirstName;
                surveyForms.LastName = original_data.LastName;
                surveyForms.DateofCreation = original_data.DateofCreation;

                surveyForms.DateofModification = DateTime.Now.ToUniversalTime();
                surveyForms.Editor = user.UserName;
                surveyForms.IPAddress = Request.UserHostAddress;
                surveyForms.MainResearchArea = mainresearcharea.MainArea;

                db.Entry(surveyForms).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(surveyForms);
        }

        // GET: SurveyForms/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // POST: SurveyForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            db.SurveyForms_Dbset.Remove(surveyForms);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public List<Professions> GetProfessionsList()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<Professions> professionsList = db.Professions_Dbset.ToList();
            return professionsList;
        }

        [HttpPost]
        public JsonResult GetSurveyCount()
        {
            var livesurveys = db.SurveyForms_Dbset;

            SurveyFormsCountViewModel livesurveycount = new SurveyFormsCountViewModel
            {
                RecordsCount = livesurveys.Count()
            };

            return Json(livesurveycount);
        }

        [HttpPost]
        public JsonResult GetMySurveyCount()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string currentusername = User.Identity.GetUserName();
            var user = db.Users.SingleOrDefault(u => u.UserName == currentusername);
            var capusername = user.UserName;

            var mylivesurveys = db.SurveyForms_Dbset.Where(s => s.UserName == capusername);

SurveyME/Views/SurveyForms/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SurveyME.Models.SurveyForms>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col">
        <div class="card surveyme-input-card mb-4 shadow">
            <div class="card-header border-0 pb-0">
                <h5 class="card-title text-center fw-bold text-success">Survey Forms</h5>
            </div>

            <div class="card-body">
                @{ int rowNo = 0; }
                @foreach (var item in Model)
                {
                    <div class="card">
                        <div class="card-header">
                            @(rowNo += 1). Survey Title - @Html.DisplayFor(modelItem => item.SurveyTitle)
                            <h6><span class="badge bg-success mt-2">@Html.DisplayFor(modelItem => item.MinistryName)</span></h6>
                            <h6><span class="badge bg-success">@Html.DisplayFor(modelItem => item.ResearchArea)</span></h6>
                        </div>

                        <div class="card-body">
                            <p class="card-text">@Html.Raw(item.SurveyDescription)</p>
                            <div>
                                <h6>Author <span class="badge bg-success">@Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)</span></h6>
                                <h6><span class="badge bg-success">@Html.DisplayFor(modelItem => item.DateofCreation)</span></h6>
                            </div>

                            <div class="float-end">
                                <p id="cap-formid" style="display:none;">@item.Id</p>
                                <p id="live-bookmarkcount" class="float-start me-2 text-success fs-14"></p>
                                <span id="my-bookmarks" style="cursor: pointer; color: gray;" class="fa fa-2x fa-bookmark"></span>
                            </div>
                        </div>
                    </div>

                    <div class="mt-3">
                        <button class="btn btn-success myBorderradius surveyme-report-button d-grid justify-content-center transform-87 me-12" type="button" @*onclick="location.href='@Url.Action("Index", "Sections", new { surveyform_id = item.Id })'"*@>Participate</button>
                    </div>
                }
            </div>

            <div>
                @Html.PagedListPager(Model, page =>
                    Url.Action("Index", new { page = page }),
                    new PagedListRenderOptions
                        {
                            UlElementClasses = new string[] { "pagination pagination-xs pagination-gutter  pagination-warning" },
                            LiElementClasses = new string[] { "page-item" },
                            LinkToPreviousPageFormat = "Previous",
                            LinkToNextPageFormat = "Next",
                            ClassToApplyToLastListItemInPager = "page-previus",
                            ClassToApplyToFirstListItemInPager = "page-next",
                            FunctionToTransformEachPageLink = (li, a) =>
                        {
                            a.AddCssClass("page-link");
                            li.InnerHtml = a.ToString();
                            return li;
                        }
                    })
            </div>
        </div>
    </div>

    <div class="col-3">
        <div class="card shadow">
            <div class="card-header">
                <h6 class="fw-bold text-success">Our Ministries</h6>
            </div>

            <div class="card-body">
                <ol class="list-group list-group-numbered">
                    @foreach (var item in ViewBag.MinistryList)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fs-14">
                                    @{
                                        string theministry = item.Ministry;
                                    }
                                    @Html.ActionLink(theministry, "MainArea", "SurveyForms", new { mainarea = item.Ministry }, null)
                                </div>
                            </div>
                            <span class="badge bg-success rounded-pill areas-stat">@item.SurveyCount</span>
                        </li>
                    }
                </ol>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $("#my-bookmarks").click(function () {
                var firstcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarks",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{formid: "' + firstcapformid + '" }',
                    success: function (response) {
                        /*console.log("Success");*/
                    },
                });
            });
        });
    </script>

    <script type="text/javascript">
        setInterval(function () {
            $(function () {
                var secondcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarksCount",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{countformid: "' + secondcapformid + '" }',
                    success: function (response) {
                        var bookmarkcount = response.BookmarkCount;
                        $('#live-bookmarkcount').text(bookmarkcount + " Interests");
                    },
                });
            });
        }, 1000);
    </script>

    <script type="text/javascript">
        setInterval(function () {
            $(function () {
                var thirdcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarksStatus",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{statusformid: "' + thirdcapformid + '" }',
                    success: function (response) {
                        var bookmarkstatus = "Yes";
                        var livebookmarkstatus = response.BookmarkStatus;
                        if (livebookmarkstatus == bookmarkstatus) {
                            $("#my-bookmarks").css("color", "#198754");
                        }
                        else {
                            $("#my-bookmarks").css("color", "gray");
                        }
                    },
                });
            });
        }, 1000);
    </script>
}

SurveyME/Views/SurveyForms/MySurveys.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SurveyME.Models.SurveyForms>

@{
    ViewBag.Title = "My Surveys";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col">
        <div class="card surveyme-input-card mb-4 shadow">
            <div class="card-header border-0 pb-0">
                <h5 class="card-title text-center fw-bold text-success">Survey Forms</h5>
            </div>

            <div class="card-body">
                @{ int cardNo = 0; }
                @foreach (var item in Model)
                {
                    <div class="card">
                        <div class="card-header">
                            @(cardNo += 1). Survey Title - @Html.DisplayFor(modelItem => item.SurveyTitle)
                            <h6><span class="badge bg-success mt-2">@Html.DisplayFor(modelItem => item.MinistryName)</span></h6>
                            <h6><span class="badge bg-success">@Html.DisplayFor(modelItem => item.ResearchArea)</span></h6>
                        </div>

                        <div class="card-body">
                            <p class="card-text">@Html.Raw(item.SurveyDescription)</p>
                            <div>
                                <h6>Author <span class="badge bg-success">@Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)</span></h6>
                                <h6><span class="badge bg-success">@Html.DisplayFor(modelItem => item.DateofCreation)</span></h6>
                            </div>
                            <button class="btn btn-success myBorderradius d-grid transform-87 me-12" type="button" onclick="location.href='@Url.Action("Edit", "SurveyForms", new { id = item.Id })'">Edit survey</button>

                            <div class="float-end">
                                <p id="cap-formid" style="display:none;">@item.Id</p>
                                <p id="live-bookmarkcount" class="float-start me-2 text-success fs-14"></p>
                                <span id="my-bookmarks" style="cursor: pointer; color: gray;" class="fa fa-2x fa-bookmark"></span>
                            </div>
                        </div>
                    </div>

                    <div class="mt-3">
                        <button class="btn btn-success myBorderradius surveyme-report-button d-grid justify-content-center transform-87 me-12" type="button" onclick="location.href='@Url.Action("Index", "Sections", new { surveyform_id = item.Id })'">Build Questionnaire</button>
                    </div>
                }
            </div>

            <div>
                @Html.PagedListPager(Model, page =>
                    Url.Action("Index", new { page = page }),
                    new PagedListRenderOptions
                        {
                            UlElementClasses = new string[] { "pagination pagination-xs pagination-gutter  pagination-warning" },
                            LiElementClasses = new string[] { "page-item" },
                            LinkToPreviousPageFormat = "Previous",
                            LinkToNextPageFormat = "Next",
                            ClassToApplyToLastListItemInPager = "page-previus",
                            ClassToApplyToFirstListItemInPager = "page-next",
                            FunctionToTransformEachPageLink = (li, a) =>
                        {
                            a.AddCssClass("page-link");
                            li.InnerHtml = a.ToString();
                            return li;
                        }
                    })
            </div>
        </div>
    </div>

    <div class="col-3">
        <div class="card shadow">
            <div class="card-header">
                <h6 class="fw-bold text-success">Our Ministries</h6>
            </div>

            <div class="card-body">
                <ol class="list-group list-group-numbered">
                    @foreach (var item in ViewBag.MinistryList)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fs-14">
                                    @{
                                        string theministry = item.Ministry;
                                    }
                                    @Html.ActionLink(theministry, "MainArea", "SurveyForms", new { mainarea = item.Ministry }, null)
                                </div>
                            </div>
                            <span class="badge bg-success rounded-pill areas-stat">@item.SurveyCount</span>
                        </li>
                    }
                </ol>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $("#my-bookmarks").click(function () {
                var firstcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarks",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{formid: "' + firstcapformid + '" }',
                    success: function (response) {
                        /*console.log("Success");*/
                    },
                });

            });
        });
    </script>

    <script type="text/javascript">
        setInterval(function () {
            $(function () {
                var secondcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarksCount",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{countformid: "' + secondcapformid + '" }',
                    success: function (response) {
                        /*console.log("Success");*/
                        var bookmarkcount = response.BookmarkCount;
                        $('#live-bookmarkcount').text(bookmarkcount + " Interests");

                    },
                });

            });
        }, 1000);
    </script>

    <script type="text/javascript">
        setInterval(function () {
            $(function () {
                var thirdcapformid = $("#cap-formid").text().toString();

                $.ajax({
                    url: "/BookmarkedSurveyForms/GetBookmarksStatus",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: '{statusformid: "' + thirdcapformid + '" }',
                    success: function (response) {
                        /*console.log("Success");*/
                        var bookmarkstatus = "Yes";
                        var livebookmarkstatus = response.BookmarkStatus;

                        if (livebookmarkstatus == bookmarkstatus) {
                            $("#my-bookmarks").css("color", "#198754");
                        }
                        else {
                            $("#my-bookmarks").css("color", "gray");
                        }

                    },
                });

            });
        }, 1000);
    </script>
}