SurveyME/Models/ResearchAreas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SurveyME.Models
{
    public class ResearchAreas
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Editor { get; set; }
        public DateTime DateofCreation { get; set; }
        public DateTime? DateofModification { get; set; }
        public string IPAddress { get; set; }
        public string MainArea { get; set; }
        public string SubArea { get; set; }
        public string Actual_ResearchArea { get; set; }
    }
}

SurveyME/Controllers/ResearchAreasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace SurveyME.Controllers
{
    public class ResearchAreasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ResearchAreas
        public ActionResult Index(int? page)
        {
            return View(db.ResearchArea_Dbset.ToList().ToPagedList(page ?? 1, 12));
        }

        // GET: ResearchAreas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResearchAreas researchAreas = await db.ResearchArea_Dbset.FindAsync(id);
            if (researchAreas == null)
            {
                return HttpNotFound();
            }
            return View(researchAreas);
        }

        // GET: ResearchAreas/Create
        public ActionResult Create()
        {
            ViewBag.mainareasList = new SelectList(GetMainAreasList(), "MainArea", "MainArea");

            return View();
        }

        // POST: ResearchAreas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserName,Editor,DateofCreation,DateofModification,IPAddress,MainArea,SubArea,Actual_ResearchArea")] ResearchAreas researchAreas)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                researchAreas.UserName = user.UserName;
                researchAreas.DateofCreation = DateTime.Now.ToUniversalTime();
                researchAreas.IPAddress = Request.UserHostAddress;

                db.ResearchArea_Dbset.Add(researchAreas);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(researchAreas);
        }

        // GET: ResearchAreas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResearchAreas researchAreas = await db.ResearchArea_Dbset.FindAsync(id);
            if (researchAreas == null)
            {
                return HttpNotFound();
            }
            return View(researchAreas);
        }

        // POST: ResearchAreas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserName,Editor,DateofCreation,DateofModification,IPAddress,MainArea,SubArea,Actual_ResearchArea")] ResearchAreas researchAreas)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var original_data = db.ResearchArea_Dbset.AsNoTracking().Where(x => x.Id == researchAreas.Id).FirstOrDefault();

                researchAreas.UserName = original_data.UserName;
                researchAreas.DateofCreation = original_data.DateofCreation;

                researchAreas.Editor = user.UserName;
                researchAreas.DateofModification = DateTime.Now.ToUniversalTime();
                researchAreas.IPAddress = Request.UserHostAddress;

                db.Entry(researchAreas).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(researchAreas);
        }

        // GET: ResearchAreas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResearchAreas researchAreas = await db.ResearchArea_Dbset.FindAsync(id);
            if (researchAreas == null)
            {
                return HttpNotFound();
            }
            return View(researchAreas);
        }

        // POST: ResearchAreas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ResearchAreas researchAreas = await db.ResearchArea_Dbset.FindAsync(id);
            db.ResearchArea_Dbset.Remove(researchAreas);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public List<ResearchAreas> GetMainAreasList()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<ResearchAreas> mainareasList = db.ResearchArea_Dbset.ToList();
            var groupedmainareas = mainareasList.GroupBy(item => item.MainArea);
            var uniquemainareaslist = groupedmainareas.Select(grp => grp.OrderBy(item => item.MainArea).First()).ToList();
            return uniquemainareaslist;
        }

        public ActionResult GetSubAreasList(string mainareaName)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<ResearchAreas> subareasList = db.ResearchArea_Dbset.Where(x => x.MainArea == mainareaName).ToList();
            var groupedsubareas = subareasList.GroupBy(item => item.SubArea);
            var uniquesubareaslist = groupedsubareas.Select(grp => grp.OrderBy(item => item.SubArea).First());
            ViewBag.SubAreaOptions = new SelectList(uniquesubareaslist, "SubArea", "SubArea");
            return PartialView("SubAreaOptionPartial");
        }

        public ActionResult GetActualAreaList(string subareaName)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<ResearchAreas> actualareasList = db.ResearchArea_Dbset.Where(x => x.SubArea.Equals(subareaName)).ToList();
            var groupedsubareas = actualareasList.GroupBy(item => item.Actual_ResearchArea);
            var uniquesubareaslist = groupedsubareas.Select(grp => grp.OrderBy(item => item.Actual_ResearchArea).First());
            ViewBag.ActualAreaOptions = new SelectList(uniquesubareaslist, "Actual_ResearchArea", "Actual_ResearchArea");
            return PartialView("ActualAreaOptionPartial");
        }

        public JsonResult GetResearchAreas(string term)
        {
            var researchareas = db.ResearchArea_Dbset.Select(q => new
            {
                Id = q.Id,
                researcharea = q.Actual_ResearchArea
            }).Where(q => q.researcharea.Contains(term));

            return Json(researchareas, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SurveyME/Views/ResearchAreas/ActualAreaOptionPartial.cshtml
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery-ui")

<option value="">Select The Actual Area</option>

@if (ViewBag.ActualAreaOptions != null)
{
    foreach (var item in ViewBag.ActualAreaOptions)
    {
        <option value="@item.Value">@item.Text </option>
    }
}

SurveyME/Views/ResearchAreas/Create.cshtml
@model SurveyME.ModelViews.UniversalViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Research Area Creator</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.DropDownListFor(model => model.ResearchAreas.MainArea, ViewBag.mainareasList as SelectList, "Select main area", new { @id = "MainArea_Data", @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the research area" })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.DropDownListFor(model => model.ResearchAreas.SubArea, new SelectList(""), "Select sub area", new { @id = "SubArea_Data", @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the survey sub area" })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.ResearchAreas.Actual_ResearchArea, new { htmlAttributes = new { @id = "ActualResearchArea_Data", @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the actual research area" } })
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Finish up</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {

            $("#MainArea_Data").change(function () {
                var mainarea = $(this).val();

                debugger
                $.ajax({
                    type: "POST",
                    url: "/ResearchAreas/GetSubAreasList?mainareaName=" + mainarea,
                    contentType: "html",
                    success: function (response) {
                        debugger
                        $("#SubArea_Data").empty();
                        $("#SubArea_Data").append(response);
                    }
                })
            })
        })
    </script>
}

SurveyME/Views/ResearchAreas/Delete.cshtml
@model SurveyME.Models.ResearchAreas

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Research Areas Editor</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="row g-4 pb-3 justify-content-center">
                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.MainArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the research area" } })
                        </div>

                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.SubArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the survey sub area" } })
                        </div>

                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.Actual_ResearchArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the actual research area" } })
                        </div>
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Delete</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SurveyME/Views/ResearchAreas/Details.cshtml
@model SurveyME.Models.ResearchAreas

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Research Areas Details Viewer</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="row g-4 pb-3 justify-content-center">
                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.MainArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the research area" } })
                        </div>

                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.SubArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the survey sub area" } })
                        </div>

                        <div class="input-group justify-content-center">
                            @Html.EditorFor(model => model.Actual_ResearchArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the actual research area" } })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SurveyME/Views/ResearchAreas/Edit.cshtml
@model SurveyME.Models.ResearchAreas

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Research Areas Editor</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.MainArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the research area" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.SubArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the survey sub area" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.Actual_ResearchArea, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the name of the actual research area" } })
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Finish up</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SurveyME/Views/ResearchAreas/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SurveyME.Models.ResearchAreas>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card surveyme-input-card mb-4 shadow">
    <div class="card-header border-0 pb-0">
        <h5 class="card-title text-center fw-bold text-success">Research Areas</h5>
    </div>

    <div class="card-body">

        @{ int rowNo = 0; }
        @foreach (var item in Model)
        {
            <div class="card mb-2">
                <div class="card-header">
                    @(rowNo += 1). @Html.DisplayFor(modelItem => item.Actual_ResearchArea) <a href="@Url.Action("Edit", "ResearchAreas", new { id = item.Id })" class="fs-14">Edit</a>
                </div>
            </div>
        }
    </div>

    <div>
        @Html.PagedListPager(Model, page =>
            Url.Action("Index", new { page = page }),
            new PagedListRenderOptions
                {
                    UlElementClasses = new string[] { "pagination pagination-xs pagination-gutter  pagination-warning" },
                    LiElementClasses = new string[] { "page-item" },
                    LinkToPreviousPageFormat = "Previous",
                    LinkToNextPageFormat = "Next",
                    ClassToApplyToLastListItemInPager = "page-previus",
                    ClassToApplyToFirstListItemInPager = "page-next",
                    FunctionToTransformEachPageLink = (li, a) =>
                {
                    a.AddCssClass("page-link");
                    li.InnerHtml = a.ToString();
                    return li;
                }
            })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SurveyME/Views/ResearchAreas/SubAreaOptionPartial.cshtml
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery-ui")

<option value="">Select The Sub Area</option>

@if (ViewBag.SubAreaOptions != null)
{
    foreach (var item in ViewBag.SubAreaOptions)
    {
        <option value="@item.Value">@item.Text </option>
    }
}