SurveyME/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace SurveyME.Controllers
{
    public class ProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Profiles
        public ActionResult Index(int? page)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string currentUserName = User.Identity.GetUserName();
            var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);
            string capturedUserName = user.UserName;

            return View(db.Profile_Dbset.Where(s => s.UserName.Equals(capturedUserName)).OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
        }

        // GET: Profiles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = await db.Profile_Dbset.FindAsync(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // GET: Profiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserName,Editor,FirstName,LastName,DateofCreation,DateofModification,IPAddress,Profession,NameofEmployer,About")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                profile.UserName = user.UserName;
                profile.FirstName = user.FirstName;
                profile.LastName = user.LastName;
                profile.DateofCreation = DateTime.Now.ToUniversalTime();
                profile.IPAddress = Request.UserHostAddress;               

                db.Profile_Dbset.Add(profile);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = await db.Profile_Dbset.FindAsync(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserName,FirstName,LastName,DateofCreation,IPAddress,Profession,NameofEmployer,About")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var original_data = db.Profile_Dbset.AsNoTracking().Where(x => x.Id == profile.Id).FirstOrDefault();

                profile.UserName = original_data.UserName;
                profile.FirstName = original_data.FirstName;
                profile.LastName = original_data.LastName;
                profile.DateofCreation = original_data.DateofCreation;

                profile.Editor = user.UserName;
                profile.DateofModification = DateTime.Now.ToUniversalTime();
                profile.IPAddress = Request.UserHostAddress;

                db.Entry(profile).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = await db.Profile_Dbset.FindAsync(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Profile profile = await db.Profile_Dbset.FindAsync(id);
            db.Profile_Dbset.Remove(profile);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SurveyME/Controllers/SurveyFormsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using SurveyME.ModelViews;

namespace SurveyME.Controllers
{
    public class SurveyFormsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SurveyForms
        public ActionResult Index(int? page)
        {
            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            return View(db.SurveyForms_Dbset.OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
        }

        public ActionResult MySurveys(int? page)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string currentUserName = User.Identity.GetUserName();
            var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);
            string capturedUserName = user.UserName;

            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            return View(db.SurveyForms_Dbset.Where(s => s.UserName.Equals(capturedUserName)).OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
        }

        public ActionResult MainArea(int? page, string theministry)
        {
            List<SurveyForms> mainList = db.SurveyForms_Dbset.ToList();

            var mainministrylist = mainList.GroupBy(x => x.MinistryName)
                .Select(x => new MinistrySurveysModelViews()
                {
                    Ministry = x.Key,
                    SurveyCount = x.Count()
                }).OrderBy(s => s.Ministry).ToList();

            ViewBag.MinistryList = mainministrylist;

            if (theministry == null)
            {
                return View(db.SurveyForms_Dbset.OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
            }
            else
            {
                return View(db.SurveyForms_Dbset.Where(s => s.MinistryName.Contains(theministry)).OrderBy(s => s.DateofCreation).ToList().ToPagedList(page ?? 1, 1));
            }
        }

        // GET: SurveyForms/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // GET: SurveyForms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SurveyForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserName,Editor,FirstName,LastName,DateofCreation,DateofModification,IPAddress,ProjectName,MinistryName,SurveyTitle,SurveyDescription,MainResearchArea,ResearchArea,Male_gender,Female_gender,Non_binary_gender,Age_group_A,Age_group_B,Age_group_C,Age_group_D,Age_group_E,Target_PWDs,Status_Single,Status_Married,Academic_Level_Primary,Academic_Level_Secondary,Academic_Level_Diploma,Academic_Level_Degree,Academic_Level_Masters,Academic_Level_PhD")] SurveyForms surveyForms)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var researcharea = surveyForms.ResearchArea;
                var mainresearcharea = db.ResearchArea_Dbset.Where(x => x.Actual_ResearchArea.Equals(researcharea)).SingleOrDefault();

                surveyForms.UserName = user.UserName;
                surveyForms.FirstName = user.FirstName;
                surveyForms.LastName = user.LastName;
                surveyForms.DateofCreation = DateTime.Now.ToUniversalTime();
                surveyForms.IPAddress = Request.UserHostAddress;
                surveyForms.MainResearchArea = mainresearcharea.MainArea;

                db.SurveyForms_Dbset.Add(surveyForms);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(surveyForms);
        }

        // GET: SurveyForms/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // POST: SurveyForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserName,Editor,FirstName,LastName,DateofCreation,DateofModification,IPAddress,ProjectName,MinistryName,SurveyTitle,SurveyDescription,MainResearchArea,ResearchArea,Male_gender,Female_gender,Non_binary_gender,Age_group_A,Age_group_B,Age_group_C,Age_group_D,Age_group_E,Target_PWDs,Status_Single,Status_Married,Academic_Level_Primary,Academic_Level_Secondary,Academic_Level_Diploma,Academic_Level_Degree,Academic_Level_Masters,Academic_Level_PhD")] SurveyForms surveyForms)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                var original_data = db.SurveyForms_Dbset.AsNoTracking().Where(x => x.Id == surveyForms.Id).FirstOrDefault();

                var researcharea = surveyForms.ResearchArea;
                var mainresearcharea = db.ResearchArea_Dbset.Where(x => x.Actual_ResearchArea.Equals(researcharea)).SingleOrDefault();

                surveyForms.UserName = original_data.UserName;
                surveyForms.FirstName = original_data.FirstName;
                surveyForms.LastName = original_data.LastName;
                surveyForms.DateofCreation = original_data.DateofCreation;

                surveyForms.DateofModification = DateTime.Now.ToUniversalTime();
                surveyForms.Editor = user.UserName;
                surveyForms.IPAddress = Request.UserHostAddress;
                surveyForms.MainResearchArea = mainresearcharea.MainArea;

                db.Entry(surveyForms).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(surveyForms);
        }

        // GET: SurveyForms/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            if (surveyForms == null)
            {
                return HttpNotFound();
            }
            return View(surveyForms);
        }

        // POST: SurveyForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SurveyForms surveyForms = await db.SurveyForms_Dbset.FindAsync(id);
            db.SurveyForms_Dbset.Remove(surveyForms);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public List<Professions> GetProfessionsList()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<Professions> professionsList = db.Professions_Dbset.ToList();
            return professionsList;
        }

        [HttpPost]
        public JsonResult GetSurveyCount()
        {
            var livesurveys = db.SurveyForms_Dbset;

            SurveyFormsCountViewModel livesurveycount = new SurveyFormsCountViewModel
            {
                RecordsCount = livesurveys.Count()
            };

            return Json(livesurveycount);
        }

        [HttpPost]
        public JsonResult GetMySurveyCount()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string currentusername = User.Identity.GetUserName();
            var user = db.Users.SingleOrDefault(u => u.UserName == currentusername);
            var capusername = user.UserName;

            var mylivesurveys = db.SurveyForms_Dbset.Where(s => s.UserName == capusername);

SurveyME/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SurveyME</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jqueryui")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/fontawesome")
    @Scripts.Render("~/bundles/myloader")
</head>
<body>
    @{ Html.RenderPartial("_NavbarPartial"); }

    <div class="container body-content body-padding">
        <div class="row">
            <div class="col-auto">
                @{ Html.RenderPartial("_SideNavPartial"); }
            </div>
            <div class="col">
                @RenderBody()
            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

SurveyME/Views/Shared/_NavBarPartial.cshtml
<nav class="navbar navbar-custom navbar-expand-lg navbar-light bg-white shadow">
    <div class="container-fluid navbar-padding">
        <a class="navbar-brand text-success" href="@Url.Action("Index", "Home")"><span class="text-success">&nbsp; Access Impact</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">White-Paper</a>
                </li>
            </ul>
            <div class="d-flex">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
</nav>

SurveyME/Views/Shared/_SideNavPartial.cshtml
@using SurveyME.Models;
@using Microsoft.AspNet.Identity;

@{
    string displayedFullName = "Join us today!";
    string displayedAbout = "At Access Impact, our goal is to create a platform that supports the process of monitoring and evaluating the output, outcome and impact of government projects.";
    string displayedProfession = "Access a project.";
}

<script src="~/Scripts/myloader.js"></script>

@if (User.Identity.IsAuthenticated)
{
    ApplicationDbContext db = new ApplicationDbContext();
    string currentUserName = User.Identity.GetUserName();

    var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);
    var about = db.Profile_Dbset.SingleOrDefault(s => s.UserName == currentUserName);
    var profession = db.Profile_Dbset.SingleOrDefault(s => s.UserName == currentUserName);

    string myabout = about.About;
    string capturedFirstName = user.FirstName;
    string capturedLastName = user.LastName;
    string capturedProfession = profession.Profession;

    displayedFullName = capturedFirstName + " " + capturedLastName;
    displayedAbout = myabout;
    displayedProfession = capturedProfession;
}

@if (!User.Identity.IsAuthenticated)
{
    displayedFullName = "Join us today";
    displayedProfession = "Access a project.";
}

<div class="card shadow sidenav-card p-2" style="width: 18rem;">
    <div class="card-body">
        @if (User.Identity.IsAuthenticated)
        {
            <h5 class="card-title fs-2 fw-bold"><a class="sidenav-link text-success" href="@Url.Action("Index", "Profiles")">@(displayedFullName)</a></h5>
        }
        @if (!User.Identity.IsAuthenticated)
        {
            <h5 class="card-title fs-2 fw-bold text-success">@(displayedFullName)</h5>
        }

        @if (User.Identity.IsAuthenticated)
        {
            <h6><span class="badge bg-success mt-2 para-length">@(displayedProfession)</span></h6>
        }
        @if (!User.Identity.IsAuthenticated)
        {
            <h6><span class="badge bg-success mt-2">@(displayedProfession)</span></h6>
        }

        <p class="card-text myabout fs-6">@(displayedAbout)</p>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <ul class="list-group list-group-flush">
            <li class="list-group-item first-link">
                <span class="fa fa-2x fa-user text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("MySurveys", "SurveyForms")">&nbsp;&nbsp; My Surveys</a>
                <span id="surveycount" class="badge bg-success rounded-pill areas-stat"></span>
            </li>
            <li class="list-group-item second-link">
                <span class="fa fa-2x fa-fire text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Index", "SurveyForms")">&nbsp;&nbsp; Explore Surveys</a>
                <span id="mysurveycount" class="badge bg-success rounded-pill areas-stat"></span>
            </li>
            <li class="list-group-item third-link">
                <span class="fa fa-2x fa-flask text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Create", "SurveyForms")">&nbsp;&nbsp; Create a Survey</a>
            </li>
            <li class="list-group-item fourth-link">
                <span class="fa fa-2x fa-yin-yang text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Create", "SurveyForms")">&nbsp;&nbsp; Participate in a Survey</a>
            </li>
        </ul>
    }

    @if (!User.Identity.IsAuthenticated)
    {
        <ul class="list-group list-group-flush">
            <li class="list-group-item second-link">
                <span class="fa fa-2x fa-fire text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Register", "Account")">&nbsp;&nbsp; Explore Surveys</a>
                <span id="exploresurveycount" class="badge bg-success rounded-pill areas-stat"></span>
            </li>
            <li class="list-group-item third-link">
                <span class="fa fa-2x fa-flask text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Register", "Account")">&nbsp;&nbsp; Create a Survey</a>
            </li>
            <li class="list-group-item fourth-link">
                <span class="fa fa-2x fa-yin-yang text-success"></span>
                <a class="sidenav-link text-success" href="@Url.Action("Register", "Account")">&nbsp;&nbsp; Participate in a Survey</a>
            </li>
        </ul>
    }

    @if (!User.Identity.IsAuthenticated)
    {
        <div class="card-body">
            <button class="btn btn-success myBorderradius" type="button" onclick="location.href='@Url.Action("Register", "Account")'">Join a survey</button>
        </div>
    }
</div>

<script type="text/javascript">
    setInterval(function () {
        $(function () {
            $.ajax({
                url: "/SurveyForms/GetSurveyCount",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: {},
                success: function (response) {
                    /*console.log("Success");*/

                    var surveycount = response.RecordsCount;
                    $('#surveycount').text(surveycount);
                    $('#exploresurveycount').text(surveycount);
                },
            });

        });
    }, 1000);
</script>

@if (User.Identity.IsAuthenticated)
{
    <script type="text/javascript">
        setInterval(function () {
            $(function () {
                $.ajax({
                    url: "/SurveyForms/GetMySurveyCount",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: {},
                    success: function (response) {
                        /*console.log("Success");*/

                        var mysurveycount = response.RecordsCount;
                        $('#mysurveycount').text(mysurveycount);

                    },
                });

            });
        }, 1000);
    </script>
}