SurveyME/Models/BinaryChoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SurveyME.Models
{
    public class BinaryChoice
    {
        public int Id { get; set; }
        public int SurveyForm_Id { get; set; }
        public int Section_Id { get; set; }
        public string UserName { get; set; }
        public string Editor { get; set; }
        public DateTime DateofCreation { get; set; }
        public DateTime? DateofModification { get; set; }
        public string IPAddress { get; set; }

        [DataType(DataType.MultilineText)]
        public string Question { get; set; }
        public string FirstOption { get; set; }
        public string SecondOption { get; set; }
    }
}

SurveyME/Controllers/BinaryChoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyME.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace SurveyME.Controllers
{
    public class BinaryChoicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BinaryChoices
        public ActionResult Index(int? page)
        {
            return View(db.BinaryChoices_Dbset.ToList().ToPagedList(page ?? 1, 12));
        }

        // GET: BinaryChoices/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BinaryChoice binaryChoice = await db.BinaryChoices_Dbset.FindAsync(id);
            if (binaryChoice == null)
            {
                return HttpNotFound();
            }
            return View(binaryChoice);
        }

        // GET: BinaryChoices/Create
        public ActionResult Create(int surveyform_id, int section_id)
        {
            int cap_surveyformid = surveyform_id;
            TempData["temp_surveyformid"] = cap_surveyformid;

            int cap_sectionid = section_id;
            TempData["temp_sectionid"] = cap_sectionid;

            return View();
        }

        // POST: BinaryChoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,SurveyForm_Id,Section_Id,UserName,Editor,DateofCreation,DateofModification,IPAddress,Question,FirstOption,SecondOption")] BinaryChoice binaryChoice)
        {
            if (ModelState.IsValid)
            {
                int passed_surveyformid = Convert.ToInt32(TempData["temp_surveyformid"]);
                int passed_sectionid = Convert.ToInt32(TempData["temp_sectionid"]);

                ApplicationDbContext db = new ApplicationDbContext();
                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);

                binaryChoice.UserName = user.UserName;
                binaryChoice.SurveyForm_Id = passed_surveyformid;
                binaryChoice.Section_Id = passed_sectionid;
                binaryChoice.DateofCreation = DateTime.Now.ToUniversalTime();
                binaryChoice.IPAddress = Request.UserHostAddress;

                db.BinaryChoices_Dbset.Add(binaryChoice);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(binaryChoice);
        }

        // GET: BinaryChoices/Edit/5
        public async Task<ActionResult> Edit(int? id, int? surveyform_Id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BinaryChoice binaryChoice = await db.BinaryChoices_Dbset.FindAsync(id);
            if (binaryChoice == null)
            {
                return HttpNotFound();
            }

            TempData["temp_surveyformid"] = surveyform_Id;
            return View(binaryChoice);
        }

        // POST: BinaryChoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,SurveyForm_Id,Section_Id,UserName,Editor,DateofCreation,DateofModification,IPAddress,Question,FirstOption,SecondOption")] BinaryChoice binaryChoice)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();

                int passed_surveyformid = Convert.ToInt32(TempData["temp_surveyformid"]);

                string currentUserName = User.Identity.GetUserName();
                var user = db.Users.SingleOrDefault(u => u.UserName == currentUserName);
                var original_data = db.BinaryChoices_Dbset.AsNoTracking().Where(x => x.Id == binaryChoice.Id).FirstOrDefault();

                binaryChoice.Editor = user.UserName;
                binaryChoice.DateofCreation = DateTime.Now.ToUniversalTime();
                binaryChoice.IPAddress = Request.UserHostAddress;

                binaryChoice.SurveyForm_Id = original_data.SurveyForm_Id;
                binaryChoice.Section_Id = original_data.Section_Id;
                binaryChoice.UserName = original_data.UserName;
                binaryChoice.DateofCreation = original_data.DateofCreation;

                db.Entry(binaryChoice).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Sections", new { surveyform_id = passed_surveyformid });
            }
            return View(binaryChoice);
        }

        // GET: BinaryChoices/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BinaryChoice binaryChoice = await db.BinaryChoices_Dbset.FindAsync(id);
            if (binaryChoice == null)
            {
                return HttpNotFound();
            }
            return View(binaryChoice);
        }

        // POST: BinaryChoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            BinaryChoice binaryChoice = await db.BinaryChoices_Dbset.FindAsync(id);
            db.BinaryChoices_Dbset.Remove(binaryChoice);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SurveyME/Views/BinaryChoices/Create.cshtml
@model SurveyME.ModelViews.UniversalViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Binary Choice Question Creator</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.BinaryChoice.Question, new { htmlAttributes = new { @class = "form-control surveyme-input-box mytext-area", @placeholder = "Enter the contents of the question" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.BinaryChoice.FirstOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the first option" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.BinaryChoice.SecondOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the second option" } })
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Finish up</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

SurveyME/Views/BinaryChoices/Delete.cshtml
@model SurveyME.Models.BinaryChoice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Delete Questions</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control surveyme-input-box mytext-area", @placeholder = "Enter the contents of the question" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.FirstOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the first option" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.SecondOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the second option" } })
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Delete</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

SurveyME/Views/BinaryChoices/Details.cshtml
@model SurveyME.Models.BinaryChoice

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Question Details Viewer</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control surveyme-input-box mytext-area", @placeholder = "Enter the contents of the question" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.FirstOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the first option" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.SecondOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the second option" } })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

SurveyME/Views/BinaryChoices/Edit.cshtml
@model SurveyME.Models.BinaryChoice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card surveyme-input-card mb-4 shadow">
        <div class="card-header border-0 pb-0">
            <h5 class="card-title text-center fw-bold text-success">Question Editor</h5>
        </div>

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="justify-content-center">
                <div class="row g-4 pb-3 justify-content-center">
                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control surveyme-input-box mytext-area", @placeholder = "Enter the contents of the question" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.FirstOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the first option" } })
                    </div>

                    <div class="input-group justify-content-center">
                        @Html.EditorFor(model => model.SecondOption, new { htmlAttributes = new { @class = "form-control surveyme-input-box myinput-text", @placeholder = "Enter the contents of the second option" } })
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" id="SaveInputData" class="btn btn-success btn-lg surveyme-report-button">Finish up</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

SurveyME/Views/BinaryChoices/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SurveyME.Models.BinaryChoice>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card surveyme-input-card mb-4 shadow">
    <div class="card-header border-0 pb-0">
        <h5 class="card-title text-center fw-bold text-success">Binary Choices Questions</h5>
    </div>

    <div class="card-body">
        @foreach (var item in Model)
        {
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="text-success">@Html.DisplayFor(modelItem => item.Question)</h5>
                </div>

                <div class="card-body">
                    <p class="card-text mb-2">1. @Html.Raw(item.FirstOption)</p>
                    <p class="card-text">2. @Html.Raw(item.SecondOption)</p>
                    <a href="@Url.Action("Edit", "BinaryChoices", new { id = item.Id })" class="fs-14">Edit the question</a>
                </div>
            </div>
        }
    </div>

    <div>
        @Html.PagedListPager(Model, page =>
            Url.Action("Index", new { page = page }),
            new PagedListRenderOptions
                {
                    UlElementClasses = new string[] { "pagination pagination-xs pagination-gutter  pagination-warning" },
                    LiElementClasses = new string[] { "page-item" },
                    LinkToPreviousPageFormat = "Previous",
                    LinkToNextPageFormat = "Next",
                    ClassToApplyToLastListItemInPager = "page-previus",
                    ClassToApplyToFirstListItemInPager = "page-next",
                    FunctionToTransformEachPageLink = (li, a) =>
                {
                    a.AddCssClass("page-link");
                    li.InnerHtml = a.ToString();
                    return li;
                }
            })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}